FROM debian:buster
ENV DEVBOX=true \
	DEBIAN_FRONTEND=noninteractive \
	TZ=Asia/Tokyo \
	TERM=xterm-256color \
	LANG=en_US.UTF-8 \
	HOMEBREW_NO_AUTO_UPDATE=1
RUN set -x -e && \
  	apt update && apt install -y \ 
		direnv kubectx make iptables zsh git man file curl tmux \
		wget sudo less locales ca-certificates iproute2 iputils-ping \
		dnsutils openssh-client build-essential procps software-properties-common && \
	sed -ie "s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen && \
	locale-gen en_US.UTF-8 && \
	apt-get clean -y && rm -rf /var/lib/apt/lists/* /var/log/* /tmp/* /var/tmp/*
RUN useradd -m -s /bin/bash linuxbrew
RUN useradd -m -s /bin/bash devbox
RUN update-alternatives --set iptables  /usr/sbin/iptables-legacy || true && \
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || true && \
    update-alternatives --set arptables /usr/sbin/arptables-legacy || true
