ARG TAG
FROM ghcr.io/uesyn/devbox-base:${TAG}
ENV GO_VERSION=1.16.3
RUN curl -L https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz | tar -C /usr/local -xzf -
ENV PATH=/usr/local/go/bin:${PATH}
