name: ci

on:
  push:
    branches: devbox-base
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  devbox-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: build and push
      run: |
        make image
        make push
