name: "Build and push devbox-base manually"
on: 
  workflow_dispatch:
jobs:
  devbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: build and push
      run: |
        cd devbox-base
        make image
        make push
